language: node_js
sudo: false
node_js:
  - 4.1
cache:
  directories:
    - output
install:
  - npm install
script:
  - travis_wait npm run build_components
  - travis_wait npm run build
  - travis_wait npm run test
