language : haskell
ghc : 7.6.3
install :
  - 'wget -O purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.6.9.5/linux64.tar.gz'
  - 'tar -xvf purescript.tar.gz'
  - 'npm install'
  - '$(npm bin)/bower update'
script :
  - 'PATH=purescript:$PATH $(npm bin)/grunt'
