language : haskell
ghc : 7.6.3
install :
  - 'cabal update'
  - 'cabal sandbox init'
  - 'cabal install purescript-0.9.5'
  - 'npm install'
  - '$(npm bin)/bower update'
script :
  - 'PATH=.cabal-sandbox/bin:$PATH $(npm bin)/grunt'
